return {
   SCREEN_WIDTH = 1024,
   SCREEN_HEIGHT = 720,
   HUD_HEIGHT = 100,

   BALL_INITIAL_RADIUS = 7.5,
   BALL_ACCELERATION = 800,
   BALL_BOUNCE_MOMENTUM_RETAIN_PERCENTAGE = 0.98,

   BALL_PARTICLES_QUANTUM_IN_MS = 10,
   BALL_PARTICLE_LIFE_TIME_IN_MS = 2000,
   BALL_PARTICLE_RADIUS = 2,

   NUM_STARTING_PEGS = 65,
   NUM_STARTING_BALLS = 10,

   PEG_RADIUS = 15,

   BUCKET_HEIGHT = 60,
   BUCKET_WIDTH = 80,
   BUCKET_WALL = 3,
   BUCKET_RADIUS = 35,

   METER_OFFSET = 369,
   
   STARTING_LOWER_WAVELENGTH = 500,
   STARTING_UPPER_WAVELENGTH = 600,

   -- The lowest visible wavelength.
   MIN_WAVELENGTH = 420,
   -- The highest visible wavelength.
   MAX_WAVELENGTH = 700,

   -- How much to increase a spectrum section by when collecting a peg
   SPECTRUM_SECTION_INCREASE = 2.5 
}
