return {
   SCREEN_WIDTH = 1024,
   SCREEN_HEIGHT = 720,
   HUD_HEIGHT = 100,

   BALL_INITIAL_RADIUS = 7.5,
   BALL_ACCELERATION = 800,
   BALL_BOUNCE_MOMENTUM_RETAIN_PERCENTAGE = 0.98,

   BALL_PARTICLES_QUANTUM_IN_MS = 1,
   BALL_PARTICLE_LIFE_TIME_IN_MS = 2000,
   BALL_PARTICLE_RANDOM_POSITION_AMOUNT = 5,
   BALL_PARTICLE_RADIUS = 2,

   NUM_STARTING_PEGS = 65,
   NUM_STARTING_BALLS = 10,

   PEG_RADIUS = 15,

   BUCKET_HEIGHT = 60,
   BUCKET_WIDTH = 80,
   BUCKET_WALL = 3,
   BUCKET_RADIUS = 20,

   -- The lowest visible wavelength.
   MIN_WAVELENGTH = 380,
   -- The highest visible wavelength.
   MAX_WAVELENGTH = 780,

   -- How much to increase a spectrum section by when collecting a peg
   SPECTRUM_SECTION_INCREASE = 6
}
