return {
   SCREEN_WIDTH = 1024,
   SCREEN_HEIGHT = 720,

   BALL_INITIAL_RADIUS = 5,
   BALL_ACCELERATION = 800,
   BALL_BOUNCE_MOMENTUM_RETAIN_PERCENTAGE = 0.98,
   PEG_RADIUS = 10,

   BUCKET_HEIGHT = 60,
   BUCKET_WIDTH = 80
}
